1.1 Create a 1d numpy array called cost price contaning the prices for 3 items.

In [2]:
import numpy as np
cost= np.array([1500,3000, 5000])
print(cost)

[1500 3000 5000]


1.2 Create a 2d numpy array called daily sales representing the number of units sold

headphones
smartphones
speakers

In [3]:
dailySales = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(dailySales)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


1.3 print the shape and dimension of both arrays.

In [4]:
np.shape(cost)

(3,)

In [5]:
print(cost.ndim)

1


In [6]:
np.shape(dailySales)


(3, 4)

In [7]:
print(dailySales.ndim)

2


2.1 the manager decides to add 2 bonus units to every product's daily sale. Add 2 to the entire daily sales array.

In [8]:
print(dailySales + 2)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


2.2 calculate total revenue each day

In [9]:
result= np.dot(cost,dailySales)
print(result)


[40000 58500 34000 56000]


2.3 Use np.sqrt() on the sales data to find the square root of all sales values for a statistical curve.

In [10]:
print(np.sqrt(dailySales))

[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


3.1 Access the sales for smartwatches(row 1)

In [11]:
print(dailySales[1])

[5 7 4 6]


3.2 Access the sales for all products for the first two days.

In [12]:
print(dailySales[:,0:2])

[[10 15]
 [ 5  7]
 [ 2  3]]


3.3 Access the sales of Speakers on Thursday specifically using double indexing.

In [13]:
print(dailySales[2][3])

4


3.4 Using slicing extract a 2x2 sub array representing sales of headphones and smartwatches for monday and tuesday

In [14]:
print(dailySales[0:2,1:3])

[[15  8]
 [ 7  4]]


4.1 Flatten the 3x4 daily sales array into a 1d array of 12 elements using .reshape().

In [15]:
reshaped_sales = dailySales.reshape(1, 12)
print(reshaped_sales)

[[10 15  8 12  5  7  4  6  2  3  2  4]]


convert the sales data into a 2x6 matrix

In [16]:
reshaped_sales = dailySales.reshape(2, 6)
print(reshaped_sales)

[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]


use np.linspace to create an array 

5.1 use np.random.randit to generate a new 3x4 array of "predicted sales" for the next week with values ranging from 0 to 20.

In [17]:
predictedSales = np.random.randint(1,21,size=(3,4))
print(predictedSales)

[[18  6  5  1]
 [20  9  7 10]
 [18 16  7  8]]


5.2 generate a random array of 5 numbers between 0 and 1 using np.random.rand.

In [21]:
arr = np.random.rand(5)
print(arr)

[0.33587562 0.73760754 0.10090833 0.43155412 0.72673318]


5.3 use np.sum to find 
1. total items sold over all 4 days
2. total items sold for each product

In [ ]:
sum = np.sum(dailySales)
print(sum)

78


In [ ]:
sum = np.sum(dailySales, axis=1)
print(sum)

[45 22 11]


In [ ]:
students = np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(avg_smarks)

NameError: name 'avg_smarks' is not defined

A1: Matadata discovery
determine shape
find total no
identify the data type of elements

In [ ]:
np.shape(avg_smarks)

(5,)

In [ ]:
np.size(students)

15

In [ ]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

A2: Data indexing & slicing
Extract all marks for the 2nd students
Extract all marks for the 3rd student across all subjects
Find the specific mark for student 1 in subject 2

In [ ]:
print(students[1])

[45 60 55]


In [ ]:
print(students[2])

[88 92 95]


In [ ]:
print(students[0][1])

85


B1 : Means and averages
calculate the avg marks for each student
calculate the avg marks for each subject

In [ ]:
avg_smarks = np.average(students, axis = 1)
print(avg_smarks)

[84.33333333 53.33333333 91.66666667 35.         70.        ]


In [ ]:
avg_marks = np.average(students, axis = 0)
print(avg_marks)

[61.2 69.4 70. ]


B2: filtering top performers
Identify and display students whose average marks are >=80

In [ ]:
top = np.where(avg_smarks >=80,avg_smarks,0)
print(top)

[84.33333333  0.         91.66666667  0.          0.        ]


B3: Gloabal adjustments
the college decides to add 5 grace marks to every subject for every student.Update the array using broadcasting

In [ ]:
print(students+5)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


C1: Pass/Fail mapping
create a status matrix
marks >= 50 - pass
marks <50 -fail

In [ ]:
marks = np.where(students >= 50,"pass", "fail")
print(marks)

[['pass' 'pass' 'pass']
 ['fail' 'pass' 'pass']
 ['pass' 'pass' 'pass']
 ['fail' 'fail' 'fail']
 ['pass' 'pass' 'pass']]


C2: Data cleaning
to standardize failing grades, replace all marks below 40 will value of 0

In [ ]:
marks = np.where(students < 40,0, students)
print(marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


D1: Grade Allocation apply a grading system baswd on the student Average
avg>=85 - grade A 
abg>= 70- grade B
avg>= 50- grade C
Below 50 - np grade

In [ ]:
grade = np.where(avg_smarks >= 85, "A", np.where(avg_smarks >= 70, "B", np.where(avg_smarks >= 50, "C", "no")))
print(grade)

['B' 'C' 'A' 'no' 'B']


E1: the copy vs view challenge
Create a backup of the marks array
Modify the original array
Check if the backup array changed or remained original

In [ ]:
backup = students.copy()
print(backup)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [ ]:
students[2][2]=18
print(students)

[[78 85 90]
 [45 60 55]
 [88 92 18]
 [30 40 35]
 [65 70 75]]


In [ ]:
print(backup)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


Case Study: 
A university moniters electricity usage (in units) of 4 hostels over 7 days
Array Name = electricity
Shape = (4,7)
rows= hostels(h1, h2, h3, h4)
cols= days(mon-sun)

A1: Create a numpy array electricuty using np.random.randint:
values between 120 and 650
shape(4,7)

In [ ]:
electricity= np.random.randint(120,650,(4,7))
print(electricity)

[[345 168 488 268 392 247 541]
 [361 466 550 376 585 170 567]
 [121 128 247 469 163 553 241]
 [442 473 470 525 222 407 394]]


A2: print the following attributes of the array:
Shape, Number of dimensions, total number of elements and data type

In [ ]:
avg_electricity = np.mean(electricity, axis=1)
print(avg_electricity)

[349.85714286 439.28571429 274.57142857 419.        ]


In [ ]:
max_consumption = np.max(electricity,axis=1)
print(max_consumption)

[541 585 553 525]


In [ ]:
max_consumption = np.max(avg_electricity)
print(max_consumption)

439.2857142857143


In [ ]:
total_consumption = np.sum(electricity,axis=0)
print(total_consumption)

[1269 1235 1755 1638 1362 1377 1743]


In [ ]:
max_cons = np.max(total_consumption)
print(max_cons)

1755


If electricity usage on any day is greater than 550 units, a 20% surcharge is applied

Create a new array penalized_usage such that
values > 550 = multiplied by 1.20
all other values remain unchanged

In [ ]:
penalized_usage = np.where(electricity>550,  electricity*1.20 ,electricity)
print(penalized_usage)


[[345.  168.  488.  268.  392.  247.  541. ]
 [361.  466.  550.  376.  702.  170.  680.4]
 [121.  128.  247.  469.  163.  663.6 241. ]
 [442.  473.  470.  525.  222.  407.  394. ]]


Compare each hostel's daily usage with its own weekly average. Create a boolean matrix where:
True: Above hostel average
False: Below or equal to hostel average

In [ ]:
avg_weekly = np.mean(electricity, axis=0)
print(avg_weekly)

[317.25 308.75 438.75 409.5  340.5  344.25 435.75]


In [ ]:
compare = np.where(electricity>avg_weekly, "True", "False")
print(compare)

[['True' 'False' 'True' 'False' 'True' 'False' 'True']
 ['True' 'True' 'True' 'False' 'True' 'False' 'True']
 ['False' 'False' 'False' 'True' 'False' 'True' 'False']
 ['True' 'True' 'True' 'True' 'False' 'True' 'False']]


Reshape the electricity data into a single row representing weekly usage(shape 1x28)
reshape the same data into 2 rows and 14 columns.

In [ ]:
reshape = electricity.reshape(1,28)
print(reshape)

[[345 168 488 268 392 247 541 361 466 550 376 585 170 567 121 128 247 469
  163 553 241 442 473 470 525 222 407 394]]


In [ ]:
reshape = electricity.reshape(2,14)
print(reshape)

[[345 168 488 268 392 247 541 361 466 550 376 585 170 567]
 [121 128 247 469 163 553 241 442 473 470 525 222 407 394]]


Copy vs view
Create ref_backup = electricity
Create safe_back = electricity.copy()
Modify one value in the original electricity array
Observe which backups change.

In [ ]:
ref_backup = electricity
print(ref_backup)

[[345 168 488 268 392 247 541]
 [361 466 550 376 585 170 567]
 [121 128 247 469 163 553 241]
 [442 473 470 525 222 407 394]]


In [ ]:
safe_backup = electricity.copy()
print(safe_backup)

[[345 168 488 268 392 247 541]
 [361 466 550 376 585 170 567]
 [121 128 247 469 163 553 241]
 [442 473 470 525 222 407 394]]


In [ ]:
electricity[3][3]= 450
print(electricity)

[[345 168 488 268 392 247 541]
 [361 466 550 376 585 170 567]
 [121 128 247 469 163 553 241]
 [442 473 470 450 222 407 394]]


In [ ]:
print(ref_backup)

[[345 168 488 268 392 247 541]
 [361 466 550 376 585 170 567]
 [121 128 247 469 163 553 241]
 [442 473 470 450 222 407 394]]


In [ ]:
print(safe_backup)

[[345 168 488 268 392 247 541]
 [361 466 550 376 585 170 567]
 [121 128 247 469 163 553 241]
 [442 473 470 525 222 407 394]]
