In [2]:
import numpy as np

Printing an array

In [3]:
# import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Printing 2d array

In [4]:
arr1 = np.array([[1,2,3],[5,6,7],[2,0,8]])
print(arr1)

[[1 2 3]
 [5 6 7]
 [2 0 8]]


Predefined functions

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Range

In [9]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,12,3)

array([ 1,  4,  7, 10])

Dividing into equal subparts

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.linspace(2,8,16)

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6, 6. , 6.4, 6.8,
       7.2, 7.6, 8. ])

In [13]:
arr= np.array([[1,3,4,5],[4,5,8,9],[3,5,8,6]])

In [14]:
print(arr.ndim) #dimension 
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(3, 4)
12
int64


Type Conversion

In [15]:
arr2 = np.array([1.2, 3.4, 5.6])
arr_int = arr.astype(int)
print(arr_int)

[[1 3 4 5]
 [4 5 8 9]
 [3 5 8 6]]


Indexing & Sciling

In [16]:
arr = np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


1D slicing

In [17]:
print(arr[1:3])
print(arr[:3])
print(arr[::2])

[20 30]
[10 20 30]
[10 30]


Sum of arrays

In [18]:
a = ([1,2,3,4],[8,6,7,9])
b= ([2,4,1,5],[6,5,3,7])
Sum = np.add(a,b)
print(Sum)

[[ 3  6  4  9]
 [14 11 10 16]]


Adding elements of array

In [19]:
Sum = np.sum(a)
print(Sum)

40


2D indexing

In [20]:
mat = np.array([[1,2,4],[2,4,5],[3,5,6]])
print(mat[2,2])
print(mat[1])

6
[2 4 5]


In [21]:
print(mat[:,1])

[2 4 5]


Updating and changing the array using copy

In [22]:
a= np.array([1,2,3])
b=a.copy()
b[2]=99
print(a)
print(b)

[1 2 3]
[ 1  2 99]


Updating the array (not safe as original array is changed)

In [23]:
a = np.array([1,2,3,4])
b = a
b[0] = 99
print(a)

[99  2  3  4]


Basic Array Operations (Vector Power)

In [24]:
a = np.array([1,3,4])
b = np.array([8,9,3])

In [25]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[ 9 12  7]
[-7 -6  1]
[ 8 27 12]
[0.125      0.33333333 1.33333333]
[1 3 1]


Scalar Operations

In [26]:
print(a+10)
print(a*2)

[11 13 14]
[2 6 8]


Universal functions (unfus)

In [27]:
arr = np.array([1,3,4,5,6])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1.         1.73205081 2.         2.23606798 2.44948974]
[0.         1.09861229 1.38629436 1.60943791 1.79175947]
[  2.71828183  20.08553692  54.59815003 148.4131591  403.42879349]
6
1
3.8
19
1.7204650534085253


Boolean indexing

In [28]:
arr = np.array([10,20,30,40,50])
print(arr[arr>29])

[30 40 50]


In [29]:
print(arr>29)

[False False  True  True  True]


Broadcasting Rule

In [30]:
# Numpy automatically expands arrays
arr = np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [32]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


Matrix Multiplication

In [33]:
A = np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [ ]:
print(A.T) #transpose

[[1 3]
 [2 4]]


Random Module

In [ ]:
np.random.rand(5) #used to generate random int


array([0.66825522, 0.74023291, 0.13379823, 0.01055589, 0.94851048])

In [38]:
np.random.rand(3,3)

array([[0.35911672, 0.91173287, 0.35551296],
       [0.13099552, 0.21727982, 0.05922053],
       [0.48129613, 0.58625962, 0.33540595]])

In [ ]:
np.random.randint(1,100,10) #random number with 10 no. of integers

array([52, 18, 57, 77,  1, 74, 33, 43, 85, 75], dtype=int32)

Reshaping Arrays

In [43]:
arr = np.arange(16)
print(arr.reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


axis in NumPy

In [45]:
arr = np.array([[1,2,3],[7,8,0]])
print(np.sum(arr))

21


In [47]:
print(np.sum(arr, axis=0)) #column wise

[ 8 10  3]


In [48]:
print(np.sum(arr, axis = 1)) #row-wise

[ 6 15]


Where in numpy

In [ ]:
arr = np.array([10,-3,4,0, 6,-9])
result = np.where(arr< 0, 0 , arr) #if condition true then zero, else output the array as it is
print(result)

[10  0  4  0  6  0]


In [52]:
arr= np.array([1,2,3,5,6])
result = np.where(arr % 2 != 0, -1, arr)
print(result)

[-1  2 -1 -1  6]


In [54]:
marks = np.array([23,45,67, 30, 87])
status = np.where(marks>50, 1, 0)
print(status)

[0 0 1 0 1]


In [58]:
data = np.array([10,20,50,70,70])
mean_val = np.mean(data)
result = np.where(data > mean_val, mean_val, data)
print(result)

[10. 20. 44. 44. 44.]


In [60]:
mat = np.array([[10,80,30],[40,50,60]])
result= np.where(mat > 50, 1, 0)
print(result)

[[0 1 0]
 [0 0 1]]
