In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3])

In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b.shape     # (2,3)

(2, 3)

In [ ]:
b.dtype

dtype('int64')

In [8]:
np.zeros((2,3))     # all zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))      # all ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(3)           # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.full((2,2), 7)   # filled with 7

array([[7, 7],
       [7, 7]])

In [12]:
np.arange(0,10,2)      # like range()

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0,1,5)     # 5 equally spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [17]:
a + b   # [5 7 9]

array([5, 7, 9])

In [19]:
a * b   # [4 10 18]

array([ 4, 10, 18])

In [20]:
a ** 2  # [1 4 9]

array([1, 4, 9])

In [22]:
np.sum(a)

np.int64(6)

In [23]:
np.mean(a)

np.float64(2.0)

In [24]:
np.min(a)

np.int64(1)

In [25]:
np.max(a)

np.int64(3)

In [26]:
np.std(a)

np.float64(0.816496580927726)

In [30]:
b = np.array([[1,2,3],
              [4,5,6]])
np.sum(b, axis=1)   # row-wise

array([ 6, 15])

In [31]:
np.sum(b, axis=0)   # column-wise

array([5, 7, 9])

In [32]:
np.max(b)

np.int64(6)

Two dimensions are compatible if:

They are equal
OR

One of them is 1

In [34]:
a = np.array([[1,2,3],
              [4,5,6]])   # shape (2,3)

b = np.array([10,20,30])  # shape (3,)
a+b

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
a = np.array([[1],[2],[3]])   # (3,1)
b = np.array([10,20,30])      # (3,)

In [35]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

A @ B

array([[19, 22],
       [43, 50]])

In [36]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [37]:
A.T

array([[1, 3],
       [2, 4]])

In [38]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [54]:
np.random.randint(5)

3

In [50]:
np.random.rand(5)        # uniform [0,1)

array([0.05044627, 0.23447739, 0.794219  , 0.94136878, 0.50044185])

In [40]:
np.random.randn(3)       # normal distribution

array([ 0.63553807,  0.98571757, -1.04178947])

In [41]:
np.random.rand(2,3)

array([[0.56337412, 0.16703415, 0.80737057],
       [0.21777493, 0.75969371, 0.94758883]])

In [51]:
np.random.randint(0,10,5)

array([2, 1, 9, 9, 3], dtype=int32)

In [52]:
np.random.seed(42)